name = "videotosrt-backend"
main = "src/worker.ts"
compatibility_date = "2026-04-30"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "videotosrt-db"
database_id = "3a5b095b-3914-443f-b256-365a4d912063"

[[r2_buckets]]
binding = "R2"
bucket_name = "r2tong0607"

[[queues.producers]]
binding = "AI_QUEUE"
queue = "videotosrt-ai-queue"

[[queues.consumers]]
queue = "videotosrt-ai-queue"
max_batch_size = 5
max_batch_timeout = 30

[vars]
SITE_NAME = "VideoToSRT"
APP_ORIGIN = "https://videotosrt.org"
AI_PROVIDER = "groq-whisper"
PAYMENT_PROVIDER = "creem"
R2_ACCOUNT_ID = "b2633e8fad738ca6375e741cf013656d"
R2_BUCKET_NAME = "r2tong0607"
R2_ENDPOINT = "https://b2633e8fad738ca6375e741cf013656d.r2.cloudflarestorage.com"
