import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { ensureUsageRecord, consumeMinutes } from '../dist/lib/credits.js';
import { effectivePlan } from '../dist/lib/stripe-entitlements.js';
const sql=new DatabaseSync(':memory:');
sql.exec(readFileSync('migrations/0001_init.sql','utf8'));
sql.exec(readFileSync('migrations/0004_stripe_billing.sql','utf8'));
const db={prepare(query){let values=[];return {bind(...v){values=v;return this;},async first(){return sql.prepare(query).get(...values)??null;},async run(){const r=sql.prepare(query).run(...values);return {meta:{changes:Number(r.changes)}};},execute(){return sql.prepare(query).run(...values);}};},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.execute());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const env={DB:db}, month=new Date().toISOString().slice(0,7);
sql.exec("INSERT INTO users (id,email,provider,provider_id,plan,created_at,updated_at) VALUES ('u','x@example.com','google','g','pro','now','now')");
sql.prepare("INSERT INTO stripe_accounts (user_id,customer_id,subscription_id,status,paid_through) VALUES ('u','cus','sub','active',?)").run(Math.floor(Date.now()/1000)+3600);
sql.prepare('INSERT INTO usage_records VALUES (?,?,?,?,?,?,?)').run('usage','u',month,25,630,'now','now');
sql.prepare('INSERT INTO stripe_quota_bases VALUES (?,?,?)').run('u',month,600);
// Lost cancellation webhook: paid-through expires while users.plan remains stale.
sql.exec('UPDATE stripe_accounts SET paid_through=1');
assert.equal(await effectivePlan(env,'u','pro'),'free');
await ensureUsageRecord(env,'u',month,'pro');
assert.equal(sql.prepare('SELECT minutes_limit FROM usage_records').get().minutes_limit,90);
await Promise.all([ensureUsageRecord(env,'u',month,'pro'),ensureUsageRecord(env,'u',month,'studio')]);
assert.equal(sql.prepare('SELECT minutes_limit FROM usage_records').get().minutes_limit,90);
assert.equal(sql.prepare('SELECT minutes_used FROM usage_records').get().minutes_used,25);
assert.equal(await consumeMinutes(env,'u',100,'stale paid request','pro'),false);
sql.prepare('UPDATE stripe_accounts SET paid_through=?').run(Math.floor(Date.now()/1000)+3600);
await ensureUsageRecord(env,'u',month,'pro');
assert.equal(sql.prepare('SELECT minutes_limit FROM usage_records').get().minutes_limit,630);
await ensureUsageRecord(env,'u',month,'studio');
assert.equal(sql.prepare('SELECT minutes_limit FROM usage_records').get().minutes_limit,630);
console.log('Stripe/backend stale quota and lost-webhook expiry integration passed');
